version: "2.0"
services:
  web:
    build: .
    command: npm start
    ports:
      - "3030:3030"
    volumes:
      - .:/api
    links:
      - mongoDB

  mongoDB:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: always
